
import { GoogleGenAI, GenerateContentResponse } from "@google/genai";

const getAIClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) throw new Error("API Key is missing from environment.");
  return new GoogleGenAI({ apiKey });
};

export const generateVisualPrompt = async (text: string, styleDescription: string): Promise<string> => {
  const ai = getAIClient();
  const response = await ai.models.generateContent({
    model: 'gemini-3-flash-preview',
    contents: `Translate this English sentence into a highly descriptive, artistic visual prompt. 
    The sentence: "${text}"
    The desired artistic style: ${styleDescription}
    Output ONLY the descriptive prompt for an image generator, no preamble.`,
  });
  return response.text || text;
};

export const generateImageWithStyle = async (
  text: string, 
  styleDescription: string
): Promise<string> => {
  const ai = getAIClient();
  
  // Use the provided style description directly
  const styleGuidance = styleDescription || "educational manga illustration, flat color style, friendly character design, clear composition, simple background, textbook illustration art";

  // Generate the actual image
  const contents: any = {
    parts: [
      { text: `Create an image for the English sentence: "${text}". Style: ${styleGuidance}. Ensure the tone and manner matches the described style. Do not include any text, words, or letters in the image. If there is a protagonist, they must be human, not an animal.` }
    ]
  };

  const response: GenerateContentResponse = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents,
    config: {
      imageConfig: {
        aspectRatio: "1:1"
      },
      // @ts-ignore
      negativePrompt: "text, english text, writing, words, letters, signature, watermark, typography, label, caption, animal, dog, cat, creature, furry, beast, pet, anthropomorphic animal"
    }
  });

  let imageUrl = '';
  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      imageUrl = `data:image/png;base64,${part.inlineData.data}`;
      break;
    }
  }

  if (!imageUrl) throw new Error("No image was generated by the model.");
  return imageUrl;
};
